//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.GymClasses = new HashSet<GymClass>();
            this.ExerciseLogs = new HashSet<ExerciseLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public short CaloriesPerHour { get; set; }
    
        public virtual ICollection<GymClass> GymClasses { get; set; }
        public virtual ICollection<ExerciseLog> ExerciseLogs { get; set; }
    }
}
