//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetRoles = new HashSet<AspNetRole>();
            this.GymClasses = new HashSet<GymClass>();
            this.GymClassBookings = new HashSet<GymClassBooking>();
            this.ExerciseLogs = new HashSet<ExerciseLog>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Discriminator { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual ICollection<GymClass> GymClasses { get; set; }
        public virtual ICollection<GymClassBooking> GymClassBookings { get; set; }
        public virtual ICollection<ExerciseLog> ExerciseLogs { get; set; }
        public virtual MedicalHistory MedicalHistory { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual Address Address { get; set; }
    }
}
