//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistory
    {
        public int Id { get; set; }
        public bool RecentlyHospitalized { get; set; }
        public bool HighBloodPressure { get; set; }
        public bool HighCholesterol { get; set; }
        public bool Diabetes { get; set; }
        public bool HeartAttackOrStroke { get; set; }
        public bool HeartConditions { get; set; }
        public bool BackProblems { get; set; }
        public string Allergies { get; set; }
        public string Medication { get; set; }
        public string Other { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
